### ISSUE TITLE
配置里的账号密码只支持小写字母

### ISSUE THREAD

**Issue by SunsetSail** [Tuisku-L/JSONAPI-NukkitX#10]
![MTlxlF.png](https://s2.ax1x.com/2019/11/22/MTlxlF.png)
如果使用大写字母会403 
---
希望支持一些变量 例如PlaceholderApi这个插件的
这样就可以获取到很多东西

**Comment by Woo0ood** [comment]
关于账号密码大小写的问题查明后进行修复.
对变量的支持暂时没有计划安排.
感谢您的反馈!

**Comment by Woo0ood** [comment]
关于账号密码大小写的问题..之前忘记回复并关闭了
测试后未复现此问题, 请提供相关代码后再提一个 Issue 吧, 感谢支持~
