### ISSUE TITLE
建议增加PlaceholderAPI支持

### ISSUE THREAD

**Issue by SinonGame** [Tuisku-L/JSONAPI-NukkitX#12]
建议增加PlaceholderAPI支持，这样基本可以获取所有插件信息，以解决部分需求
;-)

**Comment by Woo0ood** [comment]
感谢反馈, 目前暂时没有支持 Placeholder API 的计划, 未来时间充足了会考虑安排版本.
目前主要还是在等 Nukkit 发布 2.0 版本之后将插件迁移到新的架构.

**Comment by SinonGame** [comment]
好的，如果可以的话，能否给Bukkit版本增加支持呢？

**Comment by Woo0ood** [comment]
> 好的，如果可以的话，能否给 Bukkit 版本增加支持呢？

Nukkit 和 Bukkit 版本功能尽量保持一致, 若安排了支持 Placeholder API 的计划的话会一起做掉.
