### ISSUE TITLE
更新到1.16

### ISSUE THREAD

**Issue by SinonGame** [Tuisku-L/JSONAPI-NukkitX#13]
请更新以适配1.16新版本

**Comment by Woo0ood** [comment]
目前的开发计划是等待 Nukkit 发布 2.0 版本后再安排升级重构插件结构等。暂时没有继续适配 Nukkit 1.x 版本的计划。请关注 Nukkit 官方消息。

取得 iOS 版 Outlook<https://aka.ms/o0ukef>
________________________________
寄件者: AnonAlpha <notifications@github.com>
寄件日期: Sunday, June 28, 2020 10:06:51 PM
收件者: Tuisku-L/Lode.Api <Lode.Api@noreply.github.com>
副本: Subscribed <subscribed@noreply.github.com>
主旨: [Tuisku-L/Lode.Api] 更新到1.16 (#13)


请更新以适配1.16新版本

―

**Comment by SinonGame** [comment]
好的，但是Bukkit版本呢？spigot已经发布了
