### ISSUE TITLE
建议增加只读用API

### ISSUE THREAD

**Issue by SinonGame** [Tuisku-L/JSONAPI-NukkitX#7]
**建议增加只读用API，这样的话静态网站可以用只读API读取在线玩家等信息，方便网站开发**

**Comment by Woo0ood** [comment]
新发布的 [Beta 版本](https://github.com/Tuisku-L/Lode.Api/releases/tag/Beta) 已经提供了一个无需鉴权即可获取服务器最高人数和在线玩家数量的 API，同时这个 API 可以变通的用作检测服务器是否在线。

> /api/Server/GetStatus

返回值示例：
```javascript
{
    "code": 200,
    "message": "",
    "returnObject": {
        "OnlinePlayer": 0,
        "MaxPlayer": 20
    }
}
```

**Comment by SinonGame** [comment]
控制台出现错误
main ERROR Attempted to append to non-started appender Lode
同时请尽快添加HTTP-API调用方法的wiki
无法通过https访问，但在https网页中无法获取http信息，请解决

**Comment by Woo0ood** [comment]
- 控制台出现 "main ERROR Attempted to append to non-started appender Lode" 的错误暂时无需担心, 这个是因为 log4j 的 appender 问题导致, 不影响插件功能.
- 关于无法通过 https 访问的问题, 将在下一个版本中加入"支持绑定 SSL 证书" 的相关功能. 当前版本若要在 https 网页中访问请使用 Nginx 反向代理一下.
    - 另外一点说明: 其实 Lode 提供的接口本意是供后端程序调用的, 所以也没考虑跨域的问题, 所以虽然是可以直接在前端调用 API, 但是仍然建议自己在后端调用并获得数据并做出需要的处理后再转发给前端.

**Comment by SinonGame** [comment]
感谢，请尽快更新SSL证书绑定功能
希望能够增加开启CORS HEADER的功能
