### ISSUE TITLE
能否增加一个无需鉴权的接口获取所有在线玩家的ID和坐标以便与开发Nukkit版Dynmap？

### ISSUE THREAD

**Issue by SinonGame** [Tuisku-L/JSONAPI-NukkitX#8]
能否增加一个无需鉴权的接口获取所有在线玩家的ID和坐标以便与开发Nukkit版Dynmap？

**Comment by Woo0ood** [comment]
因为考虑安全因素，目前暂时不考虑在公开版本中添加除获取服务器基本信息外的无需鉴权的其他接口。如果有需要可自行添加并编译版本。

另：不建议在前端使用 JS 直接调用接口，正确的做法是通过后端正常鉴权并调用接口后返回数据给前端。

**Comment by SinonGame** [comment]
感谢，但对于我们没有php环境的小成本服务器，只能是用纯前端代码进行构建，这样的话只能是通过SHA256来保证安全

**Comment by EarthMC-BE** [comment]
还有README中的鉴权信息有问题，如果在“”外不带空格，则为
`sha256（"exampleuser/api/server/getserverInfotestpass"）= 192c2afc1a5a68d1e406d6cef243f2e10c4811556a03e25d633957d4d610123a`
如果在""外有空格，则为
`sha256（ "exampleuser/api/server/getserverInfotestpass" ）= b308c9990d9ee1149a703607d02ea7f23c2f19e651d9aa24fc5e41bc5eb12cf5`
不清楚README中的1ddc6a51b3326a88a6ff301e3ac1b588050a5d5b2ba09540d54254ae2ed7147e是如何算出的，一直在报错Error: 403 Forbidden. Timeout.

**Comment by EarthMC-BE** [comment]
对不起，我自己解决了

**Comment by SinonGame** [comment]
使用apache反向代理后，调用时提示net::ERR_EMPTY_RESPONSE

**Comment by Woo0ood** [comment]
看起来应该是反向代理的配置出了问题，不是 Lode.Api 出了问题，建议检查一下配置文件并且问一下谷歌。
